apiVersion: apps/v1
kind: Deployment
metadata:
    name: auth-service
spec:
    replicas: 1
    selector:
        matchLabels:
            app: auth-service
    template:
        metadata:
            labels:
                app: auth-service
        spec:
            containers:
                - name: auth-service
                  image: atxpaul/auth-service:latest
                  ports:
                      - containerPort: 4000
                  env:
                      - name: JWT_SECRET
                        valueFrom:
                            configMapKeyRef:
                                name: app-config
                                key: JWT_SECRET
                      - name: DB_HOST
                        valueFrom:
                            configMapKeyRef:
                                name: app-config
                                key: DB_HOST
                      - name: DB_PORT
                        valueFrom:
                            configMapKeyRef:
                                name: app-config
                                key: DB_PORT
                      - name: DB_DATABASE
                        valueFrom:
                            configMapKeyRef:
                                name: app-config
                                key: DB_DATABASE
                      - name: DB_USER
                        valueFrom:
                            secretKeyRef:
                                name: db-secret
                                key: DB_USER
                      - name: DB_PASSWORD
                        valueFrom:
                            secretKeyRef:
                                name: db-secret
                                key: DB_PASSWORD
