apiVersion: apps/v1
kind: Deployment
metadata:
    name: catalog-service
spec:
    replicas: 3
    selector:
        matchLabels:
            app: catalog-service
    template:
        metadata:
            labels:
                app: catalog-service
        spec:
            containers:
                - name: catalog-service
                  image: atxpaul/catalog-service:latest
                  ports:
                      - containerPort: 4000
                  env:
                      - name: DATABASE_URI
                        valueFrom:
                            configMapKeyRef:
                                name: catalog-config
                                key: DATABASE_URI
                      - name: DATABASE_NAME
                        valueFrom:
                            configMapKeyRef:
                                name: catalog-config
                                key: DATABASE_NAME
                      - name: PORT
                        valueFrom:
                            configMapKeyRef:
                                name: catalog-config
                                key: PORT